{% set name = "modestimage" %}
{% set version = "0.2" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "4b71af469f0c4ba73a915c6a96040cc54e81c9ce0c793e6d3e6bb72a99cb53dc" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - matplotlib
    - numpy

test:
  imports:
    - modest_image

about:
  home: The package home page
  license: MIT License
  license_family: MIT
  license_file: 'LICENSE'
  summary: Friendlier matplotlib interaction with large images

extra:
  recipe-maintainers:
    - mrakitin
