{% set year = "2019" %}
{% set cycle = "1" %}
{% set version ="1" %}

package:
  name: 11-id-chx-analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - boto3
    - chxtools
    - graphviz
    - line_profiler
    - pychx
